name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install dependencies
        run: npm ci
      - name: Linter
        run: npm run lint
      - name: Unit Test
        run: npm run test
